### ISSUE TITLE
[feature request] instead of faking mod perms, use the real mod feature as an option

### ISSUE THREAD

**Issue by Geming400** [iArtie/FakeGDMod#2]
Ok, so I've checked the code rapidly, and you are making your own mod feature
If possible, I think it could be nice as an option to show the real buttons (i'm not a geode expert, but this should be possible as you won't really be able to do mod stuff)
I don't really care if you don't want to do it, this is just a feature request after all

**Comment by iArtie** [comment]
I don't know what you mean by using the real buttons, since they are the real buttons that are used when sending a level, just of course, since when you try to send a level it tells you "Failed" and from there it removes the buttons, Obviously what I did was that instead of failed I made a success, in the entire moderation system, everything is real up to the point of sending a level, I don't believe anything at all, so I don't see the problem

**Comment by Geming400** [comment]
I know thosz were the real buttons, I just meant the real functionality
But it's pretty useless I know, u don't even know why I did this feature request, sowwy my brain can't brain at 11pm

**Comment by iArtie** [comment]
Okay, I'll think what you mean by the send buttons and so, those appear when you go to the help button and on that button there's another button that says "req" after that you can send levels and so on

**Comment by Geming400** [comment]
I already did this,  i'm going to repeat it (even tho it's useless):
- so, from what I've seen, to prevent the "failed" error (because you aren't a mod), you changed the button functionality to always say like it worked
- my idea was that there could be an option to instead use the original buttons functionality instead of overwriting it. The thing is that it's useless because:
 - well not a lot of people are mod, and people installing this mod aren't mods
 - it will do requests to the gd servers, but it will always return `-1` because of what's above 

This is just something that went through my head, and I still decided to make a feature request about it...

**Comment by iArtie** [comment]
I think I already understand what you're saying, and yes, you can't send a level like a normal mod would, it's a value that robtop gives you through the servers, Given that, the answer if you're not a mod will always be -1

**Comment by Geming400** [comment]
Ok, I found a way to do what I wanted, I just disabled the mod and the override was gone.
