### ISSUE TITLE
[FEATURE REQUEST] Add a way to stop "being" a mod

### ISSUE THREAD

**Issue by Geming400** [iArtie/FakeGDMod#3]
Ok it's a real thing this time
Because I wasn't able to remove the gd mod features, you should be able to disable it, so that you can for example then disable the mod or uninstalling it

**Comment by iArtie** [comment]
How do you the moderator system:

Put leaderboard mod and press the req button and disable the mod!

**Comment by Geming400** [comment]
Ohh yeah leaderboard mod is a thing
